apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-test-project-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-test-project-api
  template:
    metadata:
      labels:
        app: my-test-project-api
    spec:

      imagePullSecrets:
        - name: harbor-registry-secret
      containers:
        - name: api
          image: my-test-project-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: my-test-project-api-cm
            - secretRef:
                name: my-test-project-api-secret
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
