apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-test-project-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-test-project-frontend
  template:
    metadata:
      labels:
        app: my-test-project-frontend
    spec:
      imagePullSecrets:
        - name: harbor-registry-secret
      containers:
        - name: frontend
          image: my-test-project-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 10
