apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ingress.yaml
  - certificate.yaml
images:
  - name: my-test-project-api
    newName: harbor.pai-world.com/my-test-project/my-test-project-api
  - name: my-test-project-frontend
    newName: harbor.pai-world.com/my-test-project/my-test-project-frontend
